server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:e-commerce
    username: sa
    password: 
  h2:
    console: 
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: product-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
