server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:e-comerce
    username: sa
    password: 
  h2:
    console: 
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

