eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]: # Product Service route
        - id: product-service
          uri: lb://product-service
          predicates[0]:
            - Path=/api/product
      routes[1]: # Order Service route
        - id: order-service
          uri: lb://order-service
          predicates[0]:
            - Path=/api/order
      routes[2]: # Discovery Service route
        - id: discovery-server
          uri: http://localhost:8761
          predicates[0]:
            - Path=/eureka/web
          filters[0]: 
            - SetPath=/
      routes[3]: # Discovery Service Static Resources route
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates[0]:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm 
  zipkin:
    base:
      url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: 
            route:
              RouteDefinitionLocator: INFO
          gateway: TRACE
    