server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:inventory-service
    username: sa
    password: 
  h2:
    console: 
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
